GET http://localhost:3000/atendimentos

###

POST http://localhost:3000/atendimentos
Content-Type: application/x-www-form-urlencoded

cliente=Ricardo&pet=Nanny&servico=Banho&status=agendado&observacoes=Gorduchinha&data=25/10/2020